In [2]:
import torch
import numpy as np

device = "mps" if torch.mps.is_available() else "cpu"


t1 = torch.tensor([1,2,3,4], dtype=torch.float16, device=device,requires_grad=False)
type(t1)
print(t1)
t2 = torch.Tensor([1,2,3,4])
type(t2)




tensor([1., 2., 3., 4.], device='mps:0', dtype=torch.float16)


torch.Tensor

In [3]:
t1 = torch.tensor([1,2,3,4], dtype=torch.float16, device="cpu",requires_grad=False)
type(t1)
print(t1)
print(t1.device)
print(t1.shape)



tensor([1., 2., 3., 4.], dtype=torch.float16)
cpu
torch.Size([4])


In [4]:
t3 = torch.ones(3,4)
type(t3)
print(t3)
print (t3.dtype)
print(t3.device)
print(t3.requires_grad)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32
cpu
False


In [6]:
t3 = torch.ones((3,4),dtype=torch.float32, device=device)
print(t3)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='mps:0')


In [7]:
t4 = torch.rand((3,4),dtype= torch.float16)
print(t4)
print(t4.shape)

tensor([[0.9546, 0.1338, 0.7690, 0.8037],
        [0.4385, 0.1909, 0.6841, 0.4648],
        [0.8477, 0.4170, 0.8467, 0.4863]], dtype=torch.float16)
torch.Size([3, 4])


In [12]:
arr = [[1,2],[3,4]]
type(arr)
n1 = np.array(arr,dtype=np.float64) #Cpu 에서만 활동하는 데이터타입 numpy
type(n1)
print(n1)
n1[0,1]=100
print(n1)

t1 = torch.tensor(arr,dtype=torch.float32,device=device,requires_grad=True)
type(t1)

[[1. 2.]
 [3. 4.]]
[[  1. 100.]
 [  3.   4.]]


torch.Tensor

In [13]:
t1 = torch.tensor(arr,dtype=torch.float32,device=device,requires_grad=True)
type(t1)
print(t1)


tensor([[1., 2.],
        [3., 4.]], device='mps:0', requires_grad=True)


In [14]:
t2 =torch.from_numpy(n1)
type(t2)
print(t2)

tensor([[  1., 100.],
        [  3.,   4.]], dtype=torch.float64)


In [16]:
n2 = t2.numpy()
type(n2)
print(n2)

[[  1. 100.]
 [  3.   4.]]


In [18]:
n1 = np.ones((3,4))
print(n1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
t1 = torch.rand((3,3))
print(t1)

tensor([[0.0065, 0.3895, 0.0118],
        [0.9251, 0.6714, 0.8641],
        [0.5300, 0.4179, 0.7876]])


In [20]:
t1 = torch.rand((2,3,3))
print(t1)

tensor([[[0.5508, 0.4672, 0.0863],
         [0.5270, 0.1829, 0.4392],
         [0.9376, 0.5199, 0.4801]],

        [[0.8539, 0.2733, 0.3862],
         [0.6955, 0.0622, 0.8765],
         [0.4745, 0.2865, 0.8435]]])
